apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces.yaml

  - app/configmap.yaml
  - app/deployment.yaml
  - app/service.yaml

  - prometheus/configmap.yaml
  - prometheus/deployment.yaml
  - prometheus/service.yaml

  - grafana/configmap-datasource.yaml
  - grafana/deployment.yaml
  - grafana/service.yaml
